--チャンネルテーブル
CREATE TABLE channels (
  id SMALLINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  name VARCHAR(30) NOT NULL UNIQUE KEY
) DEFAULT CHARACTER SET=utf8mb4;

--番組テーブル
CREATE TABLE programs (
  id BIGINT(20) AUTO_INCREMENT NOT NULL PRIMARY KEY,
  name VARCHAR(30) NOT NULL UNIQUE KEY,
  detail VARCHAR(100) NOT NULL
) DEFAULT CHARACTER SET=utf8mb4;

--ジャンルテーブル
CREATE TABLE genres (
  id SMALLINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  name VARCHAR(30) NOT NULL UNIQUE KEY
) DEFAULT CHARACTER SET=utf8mb4;

--シーズンテーブル
CREATE TABLE seasons (
  id SMALLINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  name VARCHAR(30) NOT NULL,
  program_id BIGINT(20) NOT NULL,
    FOREIGN KEY (program_id) REFERENCES programs(id)
) DEFAULT CHARACTER SET=utf8mb4;

--エピソードテーブル
CREATE TABLE episodes (
  id BIGINT(20) AUTO_INCREMENT NOT NULL PRIMARY KEY,
  number INT NOT NULL,
  title VARCHAR(50) NOT NULL,
  detail VARCHAR(300) NOT NULL,
  length TIME NOT NULL,
  release_date DATE NOT NULL,
  view_count BIGINT(20) NOT NULL DEFAULT 0,
  season_id SMALLINT,
    FOREIGN KEY (season_id) REFERENCES seasons(id)
) DEFAULT CHARACTER SET=utf8mb4;

--アーカイブテーブル
CREATE TABLE archives (
  id BIGINT(20) AUTO_INCREMENT NOT NULL PRIMARY KEY,
  start_time DATETIME NOT NULL,
  end_time DATETIME NOT NULL,
  view_count BIGINT(20) NOT NULL,
  channel_id SMALLINT NOT NULL,
  episode_id BIGINT(20) NOT NULL,
    FOREIGN KEY (channel_id) REFERENCES channels(id),
    FOREIGN KEY (episode_id) REFERENCES episodes(id)
) DEFAULT CHARACTER SET=utf8mb4;

--チャンネルと番組を関連付けるテーブル
CREATE TABLE channel_programs (
  id BIGINT(20) AUTO_INCREMENT NOT NULL PRIMARY KEY,
  channel_id SMALLINT NOT NULL,
  program_id BIGINT(20) NOT NULL,
    FOREIGN KEY (channel_id) REFERENCES channels(id),
    FOREIGN KEY (program_id) REFERENCES programs(id)
) DEFAULT CHARACTER SET=utf8mb4;

--番組とジャンルを関連付けるテーブル
CREATE TABLE program_genres (
  id BIGINT(20) AUTO_INCREMENT NOT NULL PRIMARY KEY,
  program_id BIGINT(20) NOT NULL,
  genre_id SMALLINT NOT NULL,
    FOREIGN KEY (program_id) REFERENCES programs(id),
    FOREIGN KEY (genre_id) REFERENCES genres(id)
) DEFAULT CHARACTER SET=utf8mb4;
